### ISSUE TITLE
[BUG]: Error when i run batch udf + broadcast variable on cluster

### ISSUE THREAD

**Issue by bolcman** [dotnet/spark#597] opened 2020-07-21 22:01 UTC
Hi,

Getting the following error when I increase the number of executor-cores > 1 in my example.

i do have arrow batch function + broadcast variables.

everything works fine, when i have 1 core per executor. but when i increase it , i see this error below:

[2020-07-21T21:45:50.2508119Z] [rap-c01w07-vsny] [Error] [JvmBridge] JVM method execution failed: Nonstatic method 'save' failed for class '2695' when called with 1 arguments ([Index=1, Type=String, Value=rap_spark.output], )
[2020-07-21T21:45:50.2509611Z] [rap-c01w07-vsny] [Error] [JvmBridge] org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 23.0 failed 4 times, most recent failure: Lost task 2.3 in stage 23.0 (TID 1357, rap-c01w01-vsbh.com, executor 36): org.apache.spark.api.python.PythonException: System.IO.IOException: The process cannot access the file '/yarn/nm/usercache/svc_rap_job-dev/appcache/application_1595082415747_0382/spark-db842405-9723-4cb5-a2ed-effaa0eb8642/broadcast2489975267110409073' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Spark.Worker.Processor.BroadcastVariableProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\BroadcastVariableProcessor.cs:line 47
   at Microsoft.Spark.Worker.Processor.PayloadProcessor.Process(Stream stream) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\Processor\PayloadProcessor.cs:line 78
   at Microsoft.Spark.Worker.TaskRunner.ProcessStream(Stream inputStream, Stream outputStream, Version version, Boolean& readComplete) in D:\a\1\s\src\csharp\Microsoft.Spark.Worker\TaskRunner.cs:line 143
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:456)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:172)
	at org.apache.spark.sql.execution.python.ArrowPythonRunner$$anon$1.read(ArrowPythonRunner.scala:122)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:410)

Thanks, 
Aleks

**Comment by Niharikadutta** [comment] 2020-07-21 22:38
How are you running this spark job? Can you share the spark-submit command?

**Comment by bolcman** [comment] 2020-07-21 23:50
Sure , this is the command that i'm using, i do have a rest service on edge node that does the submission.

in this example , if i remove 
" --executor-cores=3  "
the same version works without any problem

 "sparkSubmitCommand": 
 "/opt/spark/bin/spark-submit 
 --master yarn 
 --deploy-mode cluster
 --class org.apache.spark.deploy.dotnet.DotnetRunner  
 --executor-memory=8GB 
 --driver-memory=3GB
 **--executor-cores=3**  
 --conf spark.hadoop.fs.s3a.access.key=\"%%%%%\" 
 --conf spark.hadoop.fs.s3a.endpoint=\"https://%%%%%\" 
 --conf spark.shuffle.service.enabled=\"true\" 
 --conf spark.dynamicAllocation.enabled=\"true\" 
 --conf spark.dynamicAllocation.maxExecutors=\"80\" 
 --conf spark.sql.inMemoryColumnarStorage.compressed=\"true\" 
 --conf spark.sql.inMemoryColumnarStorage.batchSize=\"10000\" 
 --conf spark.serializer=\"org.apache.spark.serializer.KryoSerializer\"
 --conf spark.kryoserializer.buffer=\"1024\" 
 --conf spark.driver.maxResultSize=\"0\" 
 --conf spark.sql.debug.maxToStringFields=\"2000\" 
 --conf spark.debug.maxToStringFields=\"2000\" 
 --conf spark.reducer.maxReqsInFlight=\"2147483646\" 
 --conf spark.sql.execution.arrow.maxRecordsPerBatch=\"2147483646\" 
 --conf spark.sql.adaptive.enabled=\"false\" 
 --conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=\"./worker/Microsoft.Spark.Worker-0.12.1\" 
 --conf spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=\"./app/Rap.Job\" 
 --conf spark.yarn.tags=\"ManualRun\" 
 --jars s3a://artifacts/dependencies/memsql/memsql-spark-connector_2.11-3.0.0-spark-2.4.4.jar,s3a://artifacts/dependencies/memsql/mariadb-java-client-2.6.0.jar,s3a://artifacts/dependencies/memsql/spray-json_2.11-1.3.5.jar 
 --archives s3a://artifacts/Rap.Job/0.1.41-beta/Rap.Job.zip#app,s3a://artifacts/dependencies/microsoft/Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.12.1.zip#worker s3a://artifacts/dependencies/microsoft/microsoft-spark-2.4.x-0.12.1.jar s3a://artifacts/Rap.Job/0.1.41-beta/Rap.Job.zip Rap.Job requestId:100"

**Comment by Niharikadutta** [comment] 2020-07-21 23:56
Thanks @bolcman  I will get back to you with my investigation.

**Comment by Niharikadutta** [comment] 2020-07-23 22:59
I am unable to reproduce this locally, could you please share your zipped up application dlls and required jars? And also the code snippet where you are declaring and using the broadcast variable? Thanks!

**Comment by imback82** [comment] 2020-07-24 19:51
@Niharikadutta when you ran this locally, did you submit it to a local standalone cluster (I think this is closer to @bolcman's yarn set up)?

@bolcman do you see the issue when you run this locally (e.g., `--master local[*]`)?

**Comment by Niharikadutta** [comment] 2020-07-24 20:50
@imback82 no I ran this in local mode using `--master local[3]`. I will run on standalone mode and update.

**Comment by bolcman** [comment] 2020-07-27 23:44
I don't see this issue locally. i see it only when i submit to cluster. 
Let me try to create a simple example for you.

**Comment by bolcman** [comment] 2020-07-31 23:43
@Niharikadutta 

sorry for the delay,  so this is the simple example,

and again, i see this error only when I submit a job to the cluster and increase the number of cores per executor.

`using Apache.Arrow;
using Microsoft.Spark.Sql;
using Microsoft.Spark.Sql.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using DF = Microsoft.Data.Analysis.DataFrame;
using StructType = Microsoft.Spark.Sql.Types.StructType;

namespace SparkExample
{

    class Program
    {
       
        static void Main(string[] args)
        {

            var spark = SparkSession.Builder()
                                    .AppName("Hello Spark!")
                                    .GetOrCreate();


            var startDate = DateTime.Today.AddYears(-20);

            var dates = new List<string>();
            while(startDate <= DateTime.Today)
            {
                dates.Add(startDate.ToString("yyyy-MM-dd"));
                startDate = startDate.AddDays(1);
            }

            var datesDF = spark.CreateDataFrame(dates);
            datesDF.PrintSchema();

   

            var dataToBroadcast = new List<string>();
            for(var i = 0; i< 100; i++)
                dataToBroadcast.Add($"{Guid.NewGuid()} No {i}");

            var toBroadcast = new ToBroadcast
            {
                BroadcastData = dataToBroadcast
            };

            var bValue = spark.SparkContext.Broadcast(toBroadcast);

            var result = datesDF.GroupBy("_1")
                .Apply(new StructType(new[] { new StructField("measure", new StringType()) }), 
                       func: inputFrame => Measure(inputFrame, bValue.Value()));

            result.Collect().ToArray();
        }


        private static DF Measure(DF inputFrame, ToBroadcast broadcastValue)
        {
            var column = inputFrame.Columns.GetArrowStringColumn("_1");
            var outputBuilder = new StringArray.Builder();

            var random = new Random(broadcastValue.BroadcastData.Count);
            foreach (var columnValues in column)
            {
                var next = random.NextDouble();
                var index = (int)(next * broadcastValue.BroadcastData.Count);
                var broadcastId = broadcastValue.BroadcastData[index];
                outputBuilder.Append($"{columnValues} - {index}");

            }
            var outputSchema = new Schema.Builder()
                                         .Field(f => f.Name("Measure").DataType(Apache.Arrow.Types.StringType.Default))
                                         .Build();

            var outputData = new IArrowArray[]
                                  {
                                   outputBuilder.Build(),
                                  };
            return DF.FromArrowRecordBatch(new RecordBatch(outputSchema, outputData, column.Count()));
        }
        
        [Serializable]
        public class ToBroadcast
        {
            public List<string> BroadcastData { get; set; }

        }
    }
}
`

**Comment by Niharikadutta** [comment] 2020-07-31 23:46
Thanks @bolcman for the example. I will submit this on a cluster and try to reproduce the issue.

**Comment by bolcman** [comment] 2020-08-04 23:26
@Niharikadutta 

i did a simple patch and re-deploy the worker, tested it a little bit and no error so far. 

![image](https://user-images.githubusercontent.com/4012644/89332190-f5f68600-d660-11ea-8660-699f2c940884.png)

**Comment by Niharikadutta** [comment] 2020-08-04 23:34
@bolcman Interesting, thanks for sharing this. I have been trying to repro the issue using my own Spark application on the cluster and using multiple executors and it worked fine. Using your above given code I have been running into some stackoverflow issues (both locally and on the cluster) and wasn't able to repro the above mentioned issue yet, I am still looking into it. But glad to see that adding `FileShare` read access worked for you and you are currently unblocked. We will check to see if this is an actual corner scenario in our code and update the code accordingly. Thanks!

**Comment by imback82** [comment] 2020-08-04 23:38
Thanks @bolcman! That looks like a valid fix. Do you want to open a PR?

**Comment by bolcman** [comment] 2020-08-05 00:03
sure , i can do that.

**Comment by imback82** [comment] 2020-08-05 00:11
Thanks @bolcman!

**Comment by imback82** [comment] 2020-08-10 04:14
Closed by #612

**Closed by imback82** 2020-08-10 04:14 UTC
Labels: bug
