### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by selvavm** [dotnet/spark#1097] opened 2022-09-05 18:50 UTC
I am thinking of developing spark enterprise application in our team and we would love to use dotnet. But this repo don’t have much commits and lot of issues are not closed. May I know is Microsoft committed to improve this?

My use case is to create a spark application with superior tooling for databricks or synapse (not yet decided but inclining towards databricks for their `databricks-connect` and local debugging). I like to do this in dotnet due to Visual Studio, Debugger, Static code analysis, Nuget, unit testing and so on. My other option is Python which I am not fond of for enterprise application.

**Comment by dbeavon** [comment] 2022-09-08 18:22
@selvavm I would recommend that you at least start by investigating synapse in Azure.  
C# is a first-class programming language for in the synapse spark environment (along with SQL, python, scala).

This was only possible due to hard work of the folks working on this project.

Synapse will run a C# solution as fast as Python, if not faster.  It was also possible to get my C# solutions running on Azure Databricks, although that product doesn't have formal support for C#.  (I opened tickets a couple times and the Databricks engineers were not eager to help.  You might be able to get databricks help from this community, but they seem to prefer to support OSS.)

Insofar as "databricks-connect" is concerned, that was an interesting feature but it's entire existence seems to be predicated on the fact that they are **unwilling to allow customers to host a databricks cluster locally**.  In the end, I was much happier after I started to run my own Apache spark clusters locally on my workstation, and I develop my .Net spark solution locally as well.   Because **synapse uses open-source-spark (OSS)** I can deploy to Azure Synapse with a very high confidence that the behavior will match my local experience.  In contrast, databricks spark is not open source and the behavior of their spark clusters (especially the driver) is not very consistent with OSS.  I had some very unusual experiences on databricks, esp. when trying to run multiple C# driver processes simultaneously within the same cluster.  (The cause of this is probably their funky "driver-daemon", running on its own asymmetric cluster node.)

**Comment by selvavm** [comment] 2022-09-09 04:59
Thanks @dbeavon. The reason I need local environment is to do debugging on huge data stored in Cloud and my laptop will not have the necessary power to process it. If Synapse also provides a local client with remote Spark, I would immediately switch.

**Comment by dbeavon** [comment] 2022-09-09 13:31
@selvavm At any given moment, I think you would have to pick between local development with small datasets (ie filtered ones), or deploy your work and use the synapse portal with the larger datasets.  

As a data developer I rarely work with large datasets until **after** deployment.  It is easy enough to compromise on the size of my datasets if I can use all my local development tools (visual studio, etc) and Windows profiling tools.

Or just get a bigger local workstation.

I am not a huge fan of **databricks-connect**.   It was not very smooth when I tried it, even when using scala and java for my development work.  Part of the problem is all the worker logic runs remotely anyway, and you can't do any sort of "debugging" to step into those bits -they are often the most important.  And I recall it was painful to constantly deploy any UDF components every time I made changes.  With .Net for spark (and a local cluster), you just hit F5 and you can debug both your driver and your executors locally as needed, with full profiling to see network, cpu, and ram.

That said, I suppose there is a market for databricks-connect.  For folks who consider themselves data scientists and use lots of local Python notebooks, then perhaps databricks-connect is a really appealing option.

**Comment by selvavm** [comment] 2022-09-09 13:51
Thanks @dbeavon. 

I can explain my use case. I have an enterprise application that has a lot of business logic and does a lot of select queries based on that logic. Similar to a traditional SQL DB application but in my case, there will be a lot of JSON files and YAML files. 

If a user complains they got Variable X as 10 instead of 100, then someone needs to step through the code and understand how variable A is transformed to X by executing multiple df.select. If there is no remote access or debugger access, then the only way to guess this transformation is based on logger which is not that interactive or productive.

**Comment by Niharikadutta** [comment] 2022-09-13 23:34
@selvavm as of today Synapse does not have a local debugging instance with remote Spark cluster. However to answer your previous question, we are actively supporting and maintaining this project in Synapse, and will soon make a new release to add Support for Spark 3.3.0. We have a lot of enterprise applications using Spark .NET running on Synapse, however if your need is for local debugging on production data, that is currently not supported on Synapse but feel free to ask any questions you might have around that on the Synapse channel ([azuresynapsediscussion@service.microsoft.com](mailto:azuresynapsediscussion@service.microsoft.com))

**Comment by selvavm** [comment] 2022-09-14 03:47
Hi @Niharikadutta. Thanks for the response. May I know if there is any plan to support local debugging using Synapse Spark? Maybe wrap the dataframe using a rest-based wrapper so that I could do a remote debugging? 

I don't know if anyone else has also requested this support but I see this will be a great addition to support enterprise development (after all, Visual Studio and dotnet is preferred for enterprise application)

**Comment by Niharikadutta** [comment] 2022-09-14 22:16
Hi @selvavm , the synapse channel would be the best place to ask this question as someone more familiar with these plans can get back to you.

**Comment by Niharikadutta** [comment] 2022-09-14 22:17
Closing this as non-issue for .NET for Apache Spark, feature related inquiry about Synapse.

**Closed by Niharikadutta** 2022-09-14 22:17 UTC
Labels: bug

**Comment by GeorgeS2019** [comment] 2023-02-14 12:38
@Niharikadutta  

This issue is SERIOUS.  many users here have serious doubts regarding .NET for Spark as First class citizen in ALL THINGS with Azure, including Azure Synapse!

Please consider re-open this issue to serve as a channel for both ways discussions
