### ISSUE TITLE
[Need Help] Aggregating a property from an array of struct

### ISSUE THREAD

**Issue by raberana** [dotnet/spark#179] opened 2019-07-18 13:21 UTC
I'm trying to aggregate a property from an array of struct using a UDF and add it as a new column.

```
root
 |-- applicationNumber: string (nullable = true)
 |-- customerInfo: struct (nullable = true)
 |    |-- contactNumber: string (nullable = true)
 |    |-- firstName: string (nullable = true)
 |    |-- lastName: string (nullable = true)
 |-- applications: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- seller: string (nullable = true)
 |    |    |-- msrp: long (nullable = true)
 |    |    |-- houseModel: string (nullable = true)
```
            Func<Column, Column> operationAggregate = Udf<StructType[], decimal>((list) =>
            {
                Console.WriteLine("aggregating");
                Console.WriteLine(list);
                // process list here, and use LINQ sum
                return 0;
            });

           df = df.WithColumn("totalPrice", operationAggregate(df["applications"]));

However, I'm not sure if this is the correct way to do the aggregation as I cannot figure out the proper input type for the UDF. This UDF throws an error:

> System.InvalidCastException: Unable to cast object of type 'Microsoft.Spark.Sql.RowConstructor' to type 'System.Object[]'.

Can't seem to find an example like this that aggregates a nested array.
There's a [scala example](https://stackoverflow.com/a/47687033/782252) but I can't figure out its equivalent to dotnet.

**Comment by rapoth** [comment] 2019-07-19 07:22
@raberana: Can you share a sample input file and an e2e sample that we could run? Also, as input to your operationAggregate, do you need the whole row or can you operate on a subset of the columns?

**Comment by raberana** [comment] 2019-07-19 08:41
hi @rapoth , i attached the sample input file. I'm thinking the input for the UDF can be a subset of columns
[sample-input.txt](https://github.com/dotnet/spark/files/3410222/sample-input.txt)

**Comment by imback82** [comment] 2019-08-06 19:58
@raberana we don't support taking a `Row` object in `Udf`s yet. But there is an ongoing work to support this. I will create an issue and reference here.

**Comment by imback82** [comment] 2019-08-06 20:01
Duplicate of #202

**Comment by imback82** [comment] 2019-11-12 21:28
@raberana we now support taking a Row object in UDF (#202). Please try it and reopen this issue if you encounter any problems.

**Closed by imback82** 2019-11-12 21:28 UTC
Labels: duplicate, enhancement
