### ISSUE TITLE
Structured streaming writing to multiple sinks

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#203] opened 2019-08-06 21:47 UTC
In my scenario i have to read from a stream perform a UDF and write the result to multiple sinks. The UDF stamps a UniqueId column which is a generated as new guid. 
 Looks like Spark is calling my UDF multiple time for each(sink), so each of the sink is getting a different value for UniqueId. Presently .net for spark, doesn't support the foreachbatch/foreach functionality from spark to fix my scenario.
 Is there any option to handle my scenario in Spark.Net.

```
inData = spark.readstream().format("eventhub")

udfdata = indata.select(from_json(myudf("column"), schema)).as("result").select(result.*)

filter1 =  udfdata.filter("column =='filter1'")
filter 2 = udfdata.filter("column =='filter2'") 

# write filter1 to two differnt sinks
filter1.writestream().format(delta).start(table1)
filter1.writestream().format(eventhub).start()

# write filter2 to two differnt sinks
filter2.writestream().format(delta).start(table2)
filter2.writestream().format(eventhub).start()
```

**Comment by imback82** [comment] 2019-08-06 23:28
Can you share C# example? 

For the example you pasted above, can you share the one that actually compiles?

**Comment by guruvonline** [comment] 2019-09-17 19:22
this is same as [issue](https://github.com/dotnet/spark/issues/208)

**Comment by imback82** [comment] 2020-01-07 03:43
Closing this as a duplicate of #208.

**Closed by imback82** 2020-01-07 03:43 UTC
Labels: enhancement
