### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by kaoutarlehlous** [dotnet/spark#844] opened 2021-03-17 13:46 UTC
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/intro/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by imback82** [comment] 2021-03-17 17:46
Closing as this seems to be a duplicate of #845.

**Closed by imback82** 2021-03-17 17:46 UTC
