### ISSUE TITLE
Add instructions on how to debug a spark.NET app launched via Visual Studio

### ISSUE THREAD

**Issue by joperezr** [dotnet/spark#289] opened 2019-10-11 03:24 UTC
This issue is to track adding documentation similar to the one over here https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/debug

@imback82 you can assign this one to me, I just logged the issue in order to not forget to do it 😄

**Comment by imback82** [comment] 2019-10-11 03:36
It's already in this repo: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application

**Comment by imback82** [comment] 2019-10-11 03:37
I am also closing this as a duplicate of #151, which I am working on now.

**Closed by imback82** 2019-10-11 03:37 UTC

**Comment by imback82** [comment] 2019-10-11 03:39
As a part of #151, I will surface it to the main README for a better discoverability.
