### ISSUE TITLE
[FEATURE REQUEST]: Ability to call UDF in scala from Spark .Net

### ISSUE THREAD

**Issue by Ragavenderan** [dotnet/spark#163] opened 2019-07-02 00:51 UTC
We have some scala implementations that are used to create data frames from raw data. 
We needed to call the user defined functions in scala to be callable from Spark .net. 
This way we can expose Spark .net connectors to query the same data frame and maintain business logic in existing scala implementation.
Example Scala code 

```scala
def loadCuratedEmailReplyPair(spark: SparkSession,
                                category: String,
                                startDateStr: String,
                                endDateStr: String,
                                path: String = "",
                                adlsRoot: String = Constants.DEFAULT_ADLS_ROOT): DataFrame = {
    CommonUtil.TryLoad(() => {
      if (logUsage) {
        Logger.logUsage(Constants.TELEMETRY_TYPE_USAGE,
                        spark.sparkContext.applicationId,
                        Dataset.ReplyPair.toString,
                        category,
                        startDateStr,
                        endDateStr,
                        Map("path" -> path, "adlsRoot" -> adlsRoot, "returnType" -> "DataSet"))
      }
      import spark.implicits._
      Category.parse(category) match {
        case Category.My =>
          loadMyData(spark, path, startDateStr, endDateStr, ReplyPair.getSchema, "msg_ReceivedDateTime")
            .map(row => Converters.ConvertReplyPair(row))
            .toDF()
        case _ => {
          extractDataFrame(spark,
                           Category.parse(category),
                           startDateStr,
                           endDateStr,
                           path,
                           adlsRoot,
                           ReplyPair.getSchema,
                           Dataset.ReplyPair,
                           Constants.DATASET_DEFAULT_FILE_FORMAT(Dataset.ReplyPair))
            .filter("msg_From is not null")
        }
      }
    })
  }
```
We want this function to be callable from Spark .Net

**Comment by imback82** [comment] 2019-07-02 06:40
Closing this as a duplicate of #115. I suggest writing a proper connector in Scala and use it via `DataFrameReader.Format`.

**Closed by imback82** 2019-07-02 06:40 UTC
Labels: duplicate
