### ISSUE TITLE
[FEATURE REQUEST]: Replacement for BinaryFormatter

### ISSUE THREAD

**Issue by GeorgeS2019** [dotnet/spark#1167] opened 2024-04-06 03:01 UTC
https://github.com/Quaver/Quaver.API/pull/153

https://github.com/dotnet/runtime/issues/98245

**Comment by dbeavon** [comment] 2024-04-17 22:11
@GeorgeS2019 
Duplicate of https://github.com/dotnet/spark/issues/1131
?

Can are you an approver with write access?  There is a PR.

**Closed** 2024-04-22 09:41 UTC
Labels: enhancement
