### ISSUE TITLE
not able to run sample on Azure databricks

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#142] opened 2019-06-14 23:11 UTC
Hi,
I am trying to run my samples in Azure databricks as job with setjar option. It's failing any not logging details of error. In application code i have try{} catch {Console.WriteLine()}. I am not able to see any error details in job logs. Any suggestion on how to do logging for troubleshooting.
bleow are the details from log
 
`- running Rserve in this R session (pid=2506), 1 server(s) --
(This session will block until Rserve is shut down)
Spark package found in SPARK_HOME: /databricks/spark
DATABRICKS_STDOUT_END-cd644a18-fa9a-4645-90b9-5e6d87a8a558-1560553321176
2019-06-14T23:02:05.685+0000: [GC (Allocation Failure) [PSYoungGen: 1832418K->247292K(1589248K)] 2071699K->649364K(5862912K), 0.2378803 secs] [Times: user=0.71 sys=0.16, real=0.24 secs] 
Executing command, time = 1560553324643.
/databricks/driver/firstapp/first.dll: 1: /databricks/driver/firstapp/first.dll: MZ����@���: not found
/databricks/driver/firstapp/first.dll: 59: /databricks/driver/firstapp/first.dll: Syntax error: Unterminated quoted string`

standard error:
`log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
19/06/14 23:02:08 ERROR Uncaught throwable from user code: org.apache.spark.SparkUserAppException: User application exited with 2
	at org.apache.spark.deploy.DotnetRunner$.main(DotnetRunner.scala:138)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command--1:1)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw$$iw$$iw$$iw$$iw.<init>(command--1:44)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw$$iw$$iw$$iw.<init>(command--1:46)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw$$iw$$iw.<init>(command--1:48)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw$$iw.<init>(command--1:50)
	at line26b4b62335d5421985181b79c967c4d825.$read$$iw.<init>(command--1:52)
	at line26b4b62335d5421985181b79c967c4d825.$read.<init>(command--1:54)
	at line26b4b62335d5421985181b79c967c4d825.$read$.<init>(command--1:58)
	at line26b4b62335d5421985181b79c967c4d825.$read$.<clinit>(command--1)
	at line26b4b62335d5421985181b79c967c4d825.$eval$.$print$lzycompute(<notebook>:7)
	at line26b4b62335d5421985181b79c967c4d825.$eval$.$print(<notebook>:6)
	at line26b4b62335d5421985181b79c967c4d825.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:199)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:590)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:545)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:190)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:323)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:303)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:230)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:268)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:303)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:591)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:586)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:477)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:544)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:383)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:330)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:216)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by imback82** [comment] 2019-06-14 23:59
This is duplicate of #121. You should `publish` your app and pass the executable name instead of `first.dll`. (You should pass `first` instead and make sure `first` executable is generated after publishing your app).

**Closed** 2019-06-15 05:28 UTC
Labels: duplicate
